### ISSUE TITLE
Agent object has no attribute get_wights

### ISSUE THREAD

**Issue by prcs** [huseinzol05/Stock-Prediction-Models#38]
Hi! first of all, congratulations for the project! I dont know if im following right the steps. But i've received the error:

> Traceback (most recent call last):
>   File "app.py", line 359, in <module>
>     minmax = minmax)
>   File "app.py", line 135, in __init__
>     self.model.get_weights(),
> AttributeError: 'Agent' object has no attribute 'get_weights'

I made:

1. Run agent.ipynb
2. I made sure it was generated the file .PKL
3. Run app.py

Thanks

**Comment by huseinzol05** [comment]
Really? I will check it.

**Comment by munkh-erdene** [comment]
Same here.

**Comment by windowshopr** [comment]
Same here. Any update on this one? Would love to get it going!

**Comment by huseinzol05** [comment]
Fixed!

**Comment by windowshopr** [comment]
Awesome! Can’t wait to try it out tonight. Thanks again for all your work!

**Comment by windowshopr** [comment]
@huseinzol05  I'm still receiving the same error? :(

EDIT: Cancel that, it seems to be working! Although when I navigate to the mentioned address (http://0.0.0.0:8005/) it says the page cannot be reached? Is this an issue with my Flask version?

EDIT: Scratch that haha seems to be working! Can't wait to figure it out :D Thanks!

**Comment by huseinzol05** [comment]
Yep, your flask.
